### ISSUE TITLE
Skill tree jumbled

### ISSUE THREAD

**Issue by absent-presence** [sbergot/mothership-assistant#1]
The skill tree doesn't seem to match what's in the PSG, and I can't seem to get Expert skills to pop up. i.e. I took piloting and it just gives me the Master skill option for Hyperspace without even showing the Expert skill Astrogation (or any other Expert skill). 
![Screenshot 2023-05-05 214357](https://user-images.githubusercontent.com/132053583/236600319-421566af-e60c-4962-ae24-d48fb5d48b8d.png)

**Comment by absent-presence** [comment]
And it's showing Mechanical Repair as an Expert skill instead of a Trained skill. 

This project is amazing though! I hope you keep at it. Our group really likes using this.

**Comment by sbergot** [comment]
Sorry for the late reply. The skill tree is using the latest version of the 1e player handbook and they have made a few changes. In this version Mechanical Repair is an expert skill. The pilot skill is a prerequisite for hyperspace and command. There is no astrogation skill:

![image](https://github.com/sbergot/mothership-assistant/assets/380656/0d2f9e91-6cf3-4415-8276-06e07bbe2b26)
