### ISSUE TITLE
Skills should apply to saves as well as stat checks.

### ISSUE THREAD

**Issue by pmfirestone** [sbergot/mothership-assistant#3]
Current behavior: skill bonuses cannot be applied to saves.

Desired behavior: skill bonuses should be usable on saves.

Justification: 
> If a character has a Skill that is relevant to the task at hand, you
can add the Skill’s bonus to the Stat *or Save* before making your roll[.] (MoSh 1e PSG, p. 19). 

> Whenever you make a Stat Check *or Save* and you have a relevant Skill, you add your Skill Bonus to your Stat *or Save*[.] (MoSh 1e PSG, p. 22)

Thanks for the great project!

**Comment by sbergot** [comment]
I agree completely. The PR is now merged. Thank you for the contribution!

**Comment by sbergot** [comment]
closed
